name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master,CoreDevelopment]
  pull_request:
    branches: [master,CoreDevelopment]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
        node-version:
          ${{ matrix.node-version }}  - run: npm ci
      - name: install modules
        run: npm install
      - name: build project
        run: npm run build:prod
      - name: install modules
        run: npm install
      - name: linting typescript
        run: npm run lint:ts
      - name: linting scss
        run: npm run lint:scss
      - name: unit testing
        run: npm run unit
      - name: unit testing
        run: npm run storybook